main/urls.py
from django.urls import path
from . import views
app_name = 'task1'

urlpatterns = [
    path('Home/', views.Homepage, name = "homepage"),
    path('login/', views.Login, name = "login"),
    path('signup/', views.Signup, name = "signup"),
    path('patient/', views.Pathome, name = "patient"),
    path('patblog/', views.Patblog, name = "patblog"),
    path('patblogdetails/<int:blogid>', views.Patblogdetails, name = "patblogdetails"),
    path('doctor/', views.Dochome, name = "doctor"),
    path('doc/', views.Doctor, name = "doc"),
    path('logout/', views.Logout, name = "logout"),
    path('dblog/', views.Doctorblog, name = "dblog"),
    path('addblog/', views.Doctoraddblog, name = "addblog"),
    path('editblog/<int:blogid>', views.Doctoreditblog, name = "editblog"),
    path('blogdetails/<int:blogid>', views.Blogdetails, name = "blogdetails"),
]    

task1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('main/', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
class Registration(models.Model):
    usertype = models.CharField(max_length=20)
    firstname = models.CharField(max_length=20, db_column='fname')
    lastname = models.CharField(max_length=20, db_column='lname')
    email = models.TextField(max_length=20, db_column='email')
    address = models.TextField(max_length=50, db_column='address')
    username = models.CharField(max_length=20, db_column='usname')
    password = models.CharField(max_length=20, db_column='pswd')
    confpassword = models.CharField(max_length=20, db_column='cnfpass')
    image = models.ImageField(upload_to='images/')

    class Meta:
        db_table = "registration"

class Blog(models.Model):
    doc_id = models.ForeignKey(Registration, on_delete=models.CASCADE, db_column='doc_id')
    title = models.CharField(max_length=20, db_column='title')      
    category = models.CharField(max_length=20, db_column='cat') 
    summary = models.TextField(max_length=50, db_column='sum')
    content = models.TextField(max_length=500, db_column='content')
    blogimage = models.ImageField(upload_to='images/')

    class Meta:
        db_table = "blog"

main/views.py
from django.shortcuts import render,redirect
from . models import *
# Create your views here.

def Homepage(request):
    return render(request, "files/home.html")

def Login(request):
    if request.method == 'POST':
        user_name = request.POST['logusername']
        pass_word = request.POST['loguserpass']
        try:
            log = Registration.objects.get(username = user_name, password = pass_word)
            request.session['session_id'] = log.id
            if log.usertype == 'Doctor':
                return redirect ('task1:doctor')
            elif(log.usertype == 'Patient'):
                return redirect ('task1:patient')
            else:
                return render (request, "files/login.html", {'fail':'Incorrect credentials'})
        except Registration.DoesNotExist:
            return render (request, "files/login.html", {'fail':'No user found'}) 
    return render(request, "files/login.html")

def Signup(request):
    message = ""
    if request.method == "POST":
        option = request.POST.get('options', None)
        f_name = request.POST['regfname']
        l_name = request.POST['reglname']
        e_mail = request.POST['regmail']
        add_ress = request.POST['regaddress']
        user_name = request.POST['regusername']
        pass_word = request.POST['regpass']
        confirm_password = request.POST['regconfpass']
        image_ = request.FILES['regimage']
        data = Registration(usertype = option, firstname = f_name, lastname = l_name, email = e_mail, address = add_ress, username = user_name, password = pass_word, confpassword = confirm_password, image = image_)
        if option == 'Doctor' or option == 'Patient':
            data.save()
            message = "Input registered successfully. Now you can login to your account."
        else:
            message = "Error. Choose usertype and try again."  
    return render(request, "files/signup.html", {'msg':message})

def Doctor(request):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        doctor = Registration.objects.filter(id = d_id).all()
        return render(request, "files/doctor.html", {'doc_data': doctor})
    else:
        return render(request, "files/login.html")

def Dochome(request):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        doctor = Registration.objects.filter(id = d_id).all()
        return render(request, "files/doctorhome.html", {'doc_data': doctor})
    else:
        return render(request, "files/login.html")

def Pathome(request):
    if 'session_id' in request.session:
        p_id = request.session['session_id']
        patient = Registration.objects.filter(id = p_id).all()
        return render(request, "files/patienthome.html", {'p_data': patient})
    else:
        return render(request, "files/login.html")
    
def Patblog(request):
    if 'session_id' in request.session:
        p_id = request.session['session_id']
        patient = Registration.objects.filter(id = p_id).all()
        blog = Blog.objects.all()
        return render(request, "files/patient_blog.html", {'p_data': patient, 'b_data': blog})
    else:
        return render(request, "files/login.html")    
    
def Patblogdetails(request,blogid):
    if 'session_id' in request.session:
        p_id = request.session['session_id']
        patient = Registration.objects.filter(id = p_id).all()
        blog = Blog.objects.filter(id=blogid)
        return render(request, "files/pat_blogdetails.html", {'p_data': patient, 'b_data': blog})
    else:
        return render(request, "files/login.html") 

def Logout(request):
    del request.session['session_id']
    return redirect ('task1:login')

def Doctorblog(request):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        doctor = Registration.objects.filter(id = d_id).all()
        blogs = Blog.objects.filter(doc_id = d_id).all()
        return render(request, "files/doctor_blog.html", {'doc_data': doctor, 'blog': blogs})
    else:
        return render(request, "files/login.html")

def Blogdetails(request,blogid):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        doctor = Registration.objects.filter(id = d_id).all()
        blogs = Blog.objects.filter(id=blogid)
        return render(request, "files/blog_details.html", {'doc_data': doctor, 'blog': blogs})
    else:
        return render(request, "files/login.html")
        
def Doctoraddblog(request):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        doc = Registration.objects.filter(id = d_id).all()
        if request.method == "POST":
            b_title = request.POST['title']
            b_category = request.POST['cat']
            b_summary = request.POST['summary']
            b_content = request.POST['content']
            b_image = request.FILES['image']
            blog = Blog(doc_id_id = d_id, title = b_title, category = b_category, summary = b_summary, content = b_content, blogimage = b_image)
            blog.save()
            return redirect ('task1:dblog')
        else:    
            return render(request, "files/doctor_addblog.html", {'doc_data': doc})
    else:
        return render(request, "files/login.html")    
    
def Doctoreditblog(request,blogid):
    if 'session_id' in request.session:
        d_id = request.session['session_id']
        blog = Blog.objects.filter(id=blogid).all()
        doc = Registration.objects.filter(id = d_id).all()
        if request.method == "POST":
            b_title1 = request.POST['title1']
            b_category1 = request.POST['cat1']
            b_summary1 = request.POST['summary1']
            b_content1 = request.POST['content1']
            b_image1 = request.FILES['image1']
            Blog.objects.filter(id=blogid).update(title = b_title1, category = b_category1, summary = b_summary1, content = b_content1, blogimage = b_image1)
            return redirect ('task1:dblog')
        else:    
            return render(request, "files/doctor_editblog.html", {'doc_data': doc, 'b_data':blog})
    else:
        return render(request, "files/login.html")     

main/templates/files/blog_details.html
<title>Doctor Blog</title>
{% extends 'files/doctor.html' %}
{% block content %}
<div class="blogdetails">
    <a href="{% url 'task1:dblog' %}"><i class="fa-solid fa-backward"></i> Back to Blogs</a><br>
    {% for blogs in blog %}
    <h2>{{blogs.title}}</h2>
    <img src="/media/{{blogs.blogimage}}" alt="" height="250px" width="250px"><br>
    <h4>Category: {{blogs.category}}</h4>
    <h5>{{blogs.summary}}</h5>
    <h5>{{blogs.content}}</h5>
    <a href="{% url 'task1:editblog' blogs.id %}" class="edit"> Edit</a>
    {% endfor %}
</div>
{% endblock %}

main/templates/files/doctor.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Home</title>
    <link rel="stylesheet" href="{% static '/doctor.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    {% for doc in doc_data %}
    <h3><u>Doctor's Dashboard</u></h3>
    <h1>Hello Dr {{doc.firstname}} {{doc.lastname}}</h1>
    <div class="container-fluid main">
        <div class="col-sm-3 sidebar">
            <img src="{{doc.image.url}}" alt="" height="200px" width="200px" style="margin: 20px 30px;"><br><br>
            <a href="{% url 'task1:doctor' %}">Home</a><br><br>
            <a href="{% url 'task1:dblog' %}">Blogs</a><br><br>
            <a href="{% url 'task1:logout' %}">Logout</a>
        </div>
        <div class="col-sm-9 menu">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    {% endfor %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

main/templates/files/doctor_addblog.html
<title>Add Blog</title>
{% extends 'files/doctor.html' %}
{% block content %}
<div class="addblog">
    <h3>Add New Blog</h3><br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="">Title</label><br>
        <input type="text" name="title" id="" required><br>
        <label for="">Category</label><br>
        <input type="text" name="cat" id="" required><br>
        <label for="">Summary</label><br>
        <textarea name="summary" id="" cols="30" rows="3" required></textarea><br>
        <label for="">Content</label><br>
        <textarea name="content" id="" cols="30" rows="6" required></textarea><br>
        <label for="">Image</label><br>
        <input type="file" name="image" id="" required><br>
        <button type="submit">Add Blog</button>
    </form>
</div>
{% endblock %}

main/templates/files/doctor_blog.html
<title>Doctor Blog</title>
{% extends 'files/doctor.html' %}
{% block content %}
<div class="container mt-5 mb-3 add">
    <a href="{% url 'task1:addblog' %}" class="new"><i class="fa-solid fa-plus"></i> New Blog</a><br><br>
    {% for blogs in blog %}
    <div class="row">
        <div class="col-lg-4 my-4">
            <div class="card" style="width: 20rem; height: 33rem; display: inline;" >
                <img src="/media/{{blogs.blogimage}}" class="card-img-top" alt="..." height="180px" width="100px">
                <div class="card-body">
                  <h5 class="card-title">{{blogs.title}} ({{blogs.category}})</h5>
                  <p class="card-text">{{blogs.summary| truncatechars:70}}<a href="{% url 'task1:blogdetails' blogs.id %}">Read More</a></p>
                </div>
              </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
    

main/templates/files/doctor_editblog.html
<title>Edit Blog</title>
{% extends 'files/doctor.html' %}
{% block content %}
<div class="addblog">
    <h3>Edit Blog Details</h3><br>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for b in b_data %}
        <label for="">Title</label><br>
        <input type="text" value="{{b.title}}" name="title1" id="" required><br>
        <label for="">Category</label><br>
        <input type="text" value="{{b.category}}" name="cat1" id="" required><br>
        <label for="">Summary</label><br>
        <textarea name="summary1" id="" cols="30" rows="3" required>{{b.summary}}</textarea><br>
        <label for="">Content</label><br>
        <textarea name="content1" id="" cols="30" rows="6" required>{{b.content}}</textarea><br>
        <label for="">Image</label><br>
        <input type="file" name="image1" id="" required><br>
        <button type="submit">Edit Blog</button>
        {% endfor %}
    </form>
</div>
{% endblock %}

main/templates/files/doctorhome.html
{% extends 'files/doctor.html' %}
{% block content %}
    <div class="dochome">
        <h3>E-mail: {{doc.email}}</h3>
        <h3>Address: {{doc.address}}</h3>
        <h3>Username: {{doc.username}}</h3>
        <h3>Password: {{doc.password}}</h3>
    </div>
{% endblock %}

main/templates/files/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="{% static '/home.css' %}">
</head>

<body">
  <header class="container-fluid header">
    <a href="#" class="logo"><h3>Home Page</h3></a>
    <nav class="nav-items">
      <a href="{% url 'task1:homepage' %}">Home</a>
      <a href="{% url 'task1:login' %}">Login</a>
      <a href="{% url 'task1:signup' %}">Sign Up</a>
    </nav>
  </header>
  <main>
    <div class="intro">
      <h1>A Hospital Portal</h1>
      <p>We are here for you.</p>
    </div>
  </main>
  <footer class="footer">
    <div class="bottom-links">
      <div class="links">
        <span>Links</span>
        <a href="{% url 'task1:homepage' %}">Home</a>
        <a href="{% url 'task1:login' %}">Login</a>
        <a href="{% url 'task1:signup' %}">Signup</a>
      </div>
      <div class="links">
        <span>Social Links</span>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
      </div>
    </div>
  </footer>
</body>

</html>

main/templates/files/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static '/login.css' %}">
</head>
<body>
    <div class="login"><br>
        <a href="{% url 'task1:homepage' %}" class="home">Home Page</a>
        <div class="login2">
            <form action="" method="post" class="form1">
                {% csrf_token %}
                <div class="heading1">
                  <h1><u>Login</u></h1>
                  <br>
                </div>
                <br><br>
                <div class="sign-group" id="cuser" >
                    <label for="">Username</label>
                    <input type="text" class="form-control sign" name="logusername" id="username" >
                    <span class="" id="usererror"></span>
                </div>
                <div class="sign-group" id="cpass">
                    <label for="">Password</label>
                    <input type="password" class="form-control sign" name="loguserpass" id="password" >
                    <span id="passerror"></span>
                </div>
                <div class="sign-group" id="cbutton">
                    <button onclick="return Logvalidate()" type="submit" class="btn btn-block signin">Sign In</button>
                </div>
                <p style="text-align: center; color: red;">{{fail}}</p>
                <div class="join">
                    <h4>Not a member? <a href="{% url 'task1:signup' %}">Join now</a></h4>
                </div>
                <br>
            </form>
        </div>    
        <br><br>
    </div>
    
    <script>
        var username_error = document.getElementById('usererror');
        var password_error = document.getElementById('passerror');
        function Logvalidate(){
            var username = document.getElementById('username').value;
            var password = document.getElementById('password').value;
            login1 = 0;
            login2 = 0;

            if (username === ""){
                document.getElementById('username').style.borderColor = "red";
                username_error.innerHTML = "Please enter your username";
                login1 = 0;
            }
            else{
                    login1 = 1;
            } 

            if (password === ""){
                document.getElementById('password').style.borderColor = "red";
                password_error.innerHTML = "Please enter your password";
                login2 = 0;
            }
            else{
                    login2 = 1;
            } 

            if(login1 === 1 && login2 == 1){
                return true;  
            }
            else{
                return false;
            }
 
        }
    </script>
</body>
</html>

main/templates/files/pat_blogdetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog Details</title>
    <link rel="stylesheet" href="{% static '/patient.css' %}">
</head>
<body>
    <a href="{% url 'task1:patblog' %}" style="float: left; color: blueviolet;">Back to Blogs</a><br>
    <div class="details">
        {% for b in b_data %}
        <h2>{{b.title}}</h2>
        <h3>Prepared by: Dr {{b.doc_id.firstname}} {{b.doc_id.lastname}}</h3>
        <img src="{{b.blogimage.url}}" alt="" height="200px" width="200px">
        <h4>Category: {{b.category}}</h4>
        <p>{{b.summary}}</p>
        <p>{{b.content}}</p>
        {% endfor %}
    </div>
</body>
</html>

main/templates/files/patient_blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blogs</title>
    <link rel="stylesheet" href="{% static '/patient.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <br>
    <h4 style="text-align: center;"><u>Blogs</u></h4>
    <a href="{% url 'task1:patient' %}" style="padding-left: 20px;">Back to Dashboard</a>
    <div class="pblog">
        <table class="table table-striped">
            <thead style="font-weight: 700;">
                <tr>
                    <th>S.No</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Summary</th>
                </tr>
            </thead>
            <tbody style="font-weight: 500;">
                {% for b in b_data %}
                <tr>
                    <td>{{b.id}}</td>
                    <td>{{b.title}}</td>
                    <td><img src="{{b.blogimage.url}}" alt="" height="200px" width="200px"></td>
                    <td>{{b.summary | truncatechars:70}}<a href="{% url 'task1:patblogdetails' b.id %}">View More</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

main/templates/files/patienthome.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Patient Home</title>
    <link rel="stylesheet" href="{% static '/patient.css' %}">
</head>
<body>
    {% for p in p_data %}
    <h2><u>Patient's Dashboard</u></h2>
    <div>
        <h1><u>Welcome {{p.firstname}} {{p.lastname}}</u></h1><br>
        <img src="{{p.image.url}}" alt="" height="200px" width="200px">
        <h3>E-mail: {{p.email}}</h3><br>
        <h3>Address: {{p.address}}</h3><br>
        <h3>Username: {{p.username}}</h3><br>
        <h3>Password: {{p.password}}</h3><br><br>   
        <a href="{% url 'task1:patblog' %}"><button>View Doctors Blog</button></a><br>
        <a href="{% url 'task1:logout' %}"><button>Logout</button></a>
    </div>
    {% endfor %}
</body>
</html>

main/templates/files/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static '/signup.css' %}">
</head>
<body>
    <div class="signup">
        <br> 
        <a href="{% url 'task1:homepage' %}" class="home">Home Page</a>
        <div class="signup2">
            <form action="" method="post" class="form1" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="heading1">
                  <h1><u><b>Sign Up</b></u></h1>
                  <br>
                </div>
                <div>
                    <select name="options" id="">
                        <option value="default">--Choose User Type--</option>
                        <option value="Patient">Patient</option>
                        <option value="Doctor">Doctor</option>
                    </select>
                </div>
                <br><br>
                <div class="sign-group">
                    <label for="">First Name</label>
                    <input type="text" name="regfname" class="form-control sign" id="FName">
                    <span class="error" id="fnamerror"></span><br>
                </div>
                <div class="sign-group">
                    <label for="">Last Name</label>
                    <input type="text" name="reglname" class="form-control sign" id="LName">
                    <span class="error" id="lnamerror"></span>
                </div>
                <div class="sign-group">
                    <label for="">Email</label>
                    <input type="text" name="regmail" class="form-control sign" id="email">
                    <span class="error" id="emailerror_"></span><br>
                </div>
                <div class="sign-group">
                    <label for="">Address</label>
                    <textarea name="regaddress" id="address" class="form-control sign" cols="30" rows="3"></textarea>
                    <span class="error" id="addresserror_"></span><br>
                </div>
                <div class="sign-group">
                    <label for="">Username</label>
                    <input type="text" name="regusername" class="form-control sign" id="user_name">
                    <span class="error" id="usererror_"></span><br>
                </div>
                <div class="sign-group">
                    <label for="">Password</label>
                    <input type="password" name="regpass" class="form-control sign" id="pass_word" minlength="8" onkeyup='check();'>*Minimum 8 characters - Uppercase,Lowercase,Numbers,Special Characters <br>
                    <span class="error" id="passerror_"></span><br>
                </div>
                <div class="sign-group">
                    <label for="">Confirm Password</label>
                    <input type="password" name="regconfpass" class="form-control sign" id="r_password" onkeyup='check();'>
                    <span class="error" id="conferror"></span><br>
                    <span id='message'></span>
                </div>
                <div class="sign-group">
                    <label for="">Choose Profile Picture</label><br>
                    <input type="file" name="regimage" class="form-control sign" id="profilepicture">
                    <span class="error" id=""></span>
                <div class="sign-group" id="cbutton">
                    <br><button onclick="return RegValidate()" type="submit" class="btn btn-block signin">Sign In</button>
                    <p style="text-align: center; color: rgba(3, 11, 235, 0.865);">{{msg}}</p>
                </div>
                <br>
                <div class="join">
                    <h4>Already a member? <a href="{% url 'task1:login' %}">Login now</a></h4>
                </div>
            </form>
        </div>    
        <br><br>
    </div>  

    <script src="{% static '/sign.js' %}"></script>
</body>
</html>